### ISSUE TITLE
Error while running teach_eval - float division by zero

### ISSUE THREAD

**Issue by msakthiganesh** [alexa/teach#26]
Hi,

I am trying to run the teach_eval command to evaluate the performance of the model for EDH by running the following command.
```
teach_eval --data_dir /scratch/smahali6/teach_edh/teach/data/ --inference_output_dir /scratch/smahali6/teach_edh/teach/data/outputs/ --split valid_seen --metrics_file /scratch/smahali6/teach_edh/teach/data/outputs/metrics/
```

Initially, I got the error below:
```
[MainThread-71052-INFO] teach.cli.eval: Evaluating split valid_seen requiring 608 files
INFO:teach.cli.eval:Evaluating split valid_seen requiring 608 files
Traceback (most recent call last):
  File "/home/smahali6/.conda/envs/teach_edh/bin/teach_eval", line 8, in <module>
    sys.exit(main())
  File "/scratch/smahali6/teach_edh/teach/src/teach/cli/eval.py", line 79, in main
    logger.info("Evaluating split %s requiring %d files" % (args.split, len(edh_instance_files)))
NameError: name 'edh_instance_files' is not defined
```
I solved it by using the line below:
`edh_instance_files =  set(os.listdir(os.path.join(args.data_dir, input_subdir, args.split)))`

Now, I get a ZeroDivisonError mentioned below:
```
[MainThread-91566-INFO] teach.cli.eval: Evaluating split valid_seen requiring 608 files
INFO:teach.cli.eval:Evaluating split valid_seen requiring 608 files
[MainThread-91566-INFO] teach.cli.eval: Evaluating split valid_seen requiring 608 files
INFO:teach.cli.eval:Evaluating split valid_seen requiring 608 files
[MainThread-91566-INFO] teach.cli.eval: Found output files for 0 instances; treating remaining 608 as failed...
INFO:teach.cli.eval:Found output files for 0 instances; treating remaining 608 as failed...
Traceback (most recent call last):
  File "/home/smahali6/.conda/envs/teach_edh/bin/teach_eval", line 8, in <module>
    sys.exit(main())
  File "/scratch/smahali6/teach_edh/teach/src/teach/cli/eval.py", line 114, in main
    results = aggregate_metrics(traj_stats, args)
  File "/scratch/smahali6/teach_edh/teach/src/teach/eval/compute_metrics.py", line 87, in aggregate_metrics
    sr = float(num_successes) / num_evals
ZeroDivisionError: float division by zero
```

Does the pipeline require any files under the output directory as `Found output files for 0 instances; treating remaining 608 as failed...`? How can I fix this and evaluate the model?

The directory tree for the project directory can be found in this link. 
[https://drive.google.com/file/d/16DrPFl-dcxbPgtbIz0ryeFZXxDRUOcIO/view?usp=sharing](https://drive.google.com/file/d/16DrPFl-dcxbPgtbIz0ryeFZXxDRUOcIO/view?usp=sharing)

Thanks!

**Comment by msakthiganesh** [comment]
Misunderstood the README file. Closing the issue.
