### ISSUE TITLE
No module named "alfred"

### ISSUE THREAD

**Issue by msakthiganesh** [alexa/teach#27]
Hi,

While running the teach_inference on the sample_model using the code below, the inference and the evaluation work fine.

```
teach_inference     
  --data_dir /Users/sakthi/Desktop/teach-main/data4/     
  --output_dir /Users/sakthi/Desktop/teach-main/data4/outputs     
  --split valid_seen     
  --metrics_file /Users/sakthi/Desktop/teach-main/data4/outputs/metrics     
  --model_module teach.inference.sample_model    
  --model_class SampleModel    
  --images_dir /Users/sakthi/Desktop/teach-main/data4/images/
```

But, while trying to run it with the ET models using the code below, it throws the error "No module named 'alfred'".

```
teach_inference     
  --data_dir /Users/sakthi/Desktop/teach-main/data4/     
  --output_dir /Users/sakthi/Desktop/teach-main/data4/outputs     
  --split valid_seen     
  --metrics_file /Users/sakthi/Desktop/teach-main/data4/outputs/metrics    
   --model_module teach.inference.et_model    
  --model_class ETModel     
  --images_dir /Users/sakthi/Desktop/teach-main/data4/images/ 
  --model_dir /Users/sakthi/Desktop/teach-main/data4/baseline_models/et 
  --object_predictor /Users/sakthi/Desktop/teach-main/data4/et_pretrained_models/maskrcnn_model.pth     
  --visual_checkpoint /Users/sakthi/Desktop/teach-main/data4/et_pretrained_models/fasterrcnn_model.pth
```

Error:
```
Traceback (most recent call last):
  File "/Users/sakthi/opt/anaconda3/envs/teach_edh/bin/teach_inference", line 8, in <module>
    sys.exit(main())
  File "/Users/sakthi/Desktop/teach-main/src/teach/cli/inference.py", line 150, in main
    model_class=dynamically_load_class(args.model_module, args.model_class),
  File "/Users/sakthi/Desktop/teach-main/src/teach/utils.py", line 390, in dynamically_load_class
    module = __import__(package_path, fromlist=[class_name])
  File "/Users/sakthi/Desktop/teach-main/src/teach/inference/et_model.py", line 11, in <module>
    from alfred import constants
ModuleNotFoundError: No module named 'alfred'
```
Could you please let me know how to solve it? Or add the required alfred package to the requirements?

Thanks!

**Comment by aishwaryap** [comment]
Hi,

You can resolve that error by updating your `PYTHONPATH` as follows before running `teach_inference`
```
export TEACH_DIR=<path/to/teach>
export PYTHONPATH=$TEACH_DIR/src/tech/modeling/ET:$PYTHONPATH
```

Best,
Aishwarya
