### ISSUE TITLE
User-friendly API for manipulating the data

### ISSUE THREAD

**Issue by aleSuglia** [alexa/teach#3]
Hi @aishwaryap,

Thanks for releasing your dataset. I was wondering whether you had a way to manipulate the low-level JSON data in a more user-friendly way. I can see from the codebase that there is a `Dataset` class that exposes a `from_dict()` method which is supposed to be used to create a `Dataset` object from a `Dict`. However, I'm currently having the following issue when doing so:

```python
>>> with open("/tmp/teach/games/train/8cdf3d9a18cac7fe_6b02.game.json") as in_file:
            game = json.load(in_file)
>>> dataset = Dataset.from_dict(game)

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/asuglia/workspace/teach/src/teach/dataset/dataset.py", line 47, in from_dict
    tasks = [
  File "/Users/asuglia/workspace/teach/src/teach/dataset/dataset.py", line 48, in <listcomp>
    Task.from_dict(task_dict, definitions, process_init_state) for task_dict in dataset_dict.get("tasks")
  File "/Users/asuglia/workspace/teach/src/teach/dataset/task.py", line 35, in from_dict
    episodes = [
  File "/Users/asuglia/workspace/teach/src/teach/dataset/task.py", line 36, in <listcomp>
    Episode.from_dict(episode_dict, definitions, process_init_state)
  File "/Users/asuglia/workspace/teach/src/teach/dataset/episode.py", line 60, in from_dict
    initial_state=Initialization.from_dict(episode_dict["initial_state"])
  File "/Users/asuglia/workspace/teach/src/teach/dataset/initialization.py", line 47, in from_dict
    agents = [Pose_With_ID.from_dict(x) for x in initialization_dict["agents"]]
  File "/Users/asuglia/workspace/teach/src/teach/dataset/initialization.py", line 47, in <listcomp>
    agents = [Pose_With_ID.from_dict(x) for x in initialization_dict["agents"]]
  File "/Users/asuglia/workspace/teach/src/teach/dataset/pose.py", line 60, in from_dict
    return cls(identity=identity, pose=Pose.from_array(pose_with_id_dict["pose"]), is_object=is_object)
KeyError: 'pose'
```

In general, I would love to have a more object-oriented way of handling the data. I could write my own parser of the JSON data but I believe this logic must be somewhere already in your codebase. Potentially having an example script with an example showing how to explore the dataset might be useful to others as well. Any thoughts?

**Comment by aishwaryap** [comment]
@aleSuglia I have addressed this in commit [7f9e4cf8d27c0aaafef168e52750e90e8fbbf043](https://github.com/alexa/teach/commit/7f9e4cf8d27c0aaafef168e52750e90e8fbbf043)
There was a bug preventing loading of game files in the way you tried but it is enabled now. There are some limitations to what you can do with that representation though, and I have tried to document them in `src/teach/analysis/teach_data_exploration.ipynb`
